name: Release Tag Artifacts

on: 
  push:
    tags:
      - v*
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7.7'
          architecture: 'x64'
    - name: Install Requirements
      run: pip install -r requirements.txt
    - name: Build PyInstaller
      run: python setup.py pyinstaller
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: ./dist/picta-dl.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.5.4'
          architecture: 'x64'
    - name: Build Binary Distribution
      run: python setup.py bdist bdist_wheel
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args: ./dist/picta_dl*.tar.gz ./dist/picta_dl*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
